<?
define("VP_TEB_URL",'https://tes.teb.com.tr/kurumsal/VPOSMessageServer.do');
define("VP_TEB_SHOPID",'000000000029279');
define("VP_TEB_TERMINALID",'PS046792');
define("VP_TEB_SELLCODE",3001);
define("VP_TEB_CANCELCODE",3002);
define("VP_TEB_REBATECODE",3010);
define("VP_TEB_REBATECANCELCODE",3011);

define("VP_CURRENT",2);

//define("VP_FORTIS_URL",'https://vpos.est.com.tr/servlet/cc5ApiServer');
//define("VP_FORTIS_NAME",'kostiga');
//define("VP_FORTIS_PASSWORD",'TRps2730');
//define("VP_FORTIS_CLIENTID",'202422730');
define("VP_FORTIS_MODE",'P');
define("VP_FORTIS_TYPE",'Auth');
define("VP_FORTIS_CURRENCY",'949');
/*
define("VP_FORTIS_URL", "https://spos.isbank.com.tr/servlet/cc5ApiServer");
//define("POS_3D_GATEURL", "https://spos.isbank.com.tr/servlet/est3Dgate");
define("VP_FORTIS_CLIENTID", "734016010"); // //722041010
define("VP_FORTIS_NAME", "oknihapi"); // //adhood
define("VP_FORTIS_PASSWORD", "oK2023Hh"); //yUtZ123y
*/
define("VP_FORTIS_URL", "https://vpos.est.com.tr/servlet/cc5ApiServer");
define("VP_FORTIS_CLIENTID", "105312710"); // //722041010
define("VP_FORTIS_NAME", "KO1212api"); // //adhood
define("VP_FORTIS_PASSWORD", "34KO08yt"); //yUtZ123y
//
//define("POS_3D_STOREKEY", "zU12Tt43");
//define("POS_3D_CURRENCY", "949");
//define("POS_3D_STORETYPE", "3d");
?>